name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      # - name: Run tests
      #   run: bun test

      - name: Run ESLint
        run: bun run lint

      - name: Check Prettier formatting
        run: bun run format:check

  build:
    needs: test_and_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.sha }}

# TODO: setup automated deploy to the cloud
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v1
  #       with:
  #         bun-version: latest

  #     - name: Cache dependencies
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.bun/install/cache
  #         key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
  #         restore-keys: |
  #           ${{ runner.os }}-bun-

  #     - name: Install dependencies
  #       run: bun install

  #     - name: Restore build
  #       uses: actions/cache@v4
  #       with:
  #         path: build
  #         key: ${{ runner.os }}-build-${{ github.sha }}

  #     - name: Use secret API key
  #       run: echo ${{ secrets.API_KEY }}

  #     - name: Deploy to production
  #       run: bun run deploy